### ISSUE TITLE
Deploy wordpress and reconfigure 

### ISSUE THREAD

**Issue by SharifAbdulcoder** [fuchicorp/kubernetes#81]
Please attach fuchicorp.com to wordpress host. Whenver anyone goes to fuchicorp.com it should redirect to wordpress deployment. Please let me know if you any questions and don't forget to create PR. 
Please change PVC to 10g 
Steps: 
1. Use existing wordpress deployment from @neshimbekova 's example 
2. Attach fuchicorp.com under wordpress deployment

https://github.com/fuchicorp/kubernetes/blob/7c9c044997e85b31db85934c05de1673a7031628/ingress.yaml#L12

**Comment by alibek17** [comment]
wordpress deployment namespace - prod
port - 7102
